stages:
  - build
  - validate
  - clean
  - deploy

include:
  - project: 'team-scp/tools-for-ci-cd'
    file: 'checkpackages.yml'

### VARIABLES ###
# lowercase variables = local vars
# uppercase variables = CI-CD Secret vars or Git vars

variables:

## checkpackage variables
  img_tag: ${CI_COMMIT_TAG}
  img_name: ${CI_PROJECT_PATH}
  registry_url: "service-tms-docker.artifactory.si.francetelecom.fr"
  registry_user: "${REGISTRY_USER}"
  registry_pass: "${REGISTRY_PASS}"
  pushlatest: "True"
  pushimage: "True"
  pushlongtag: "True"
  version_from_tag: "True"
  repository: "service-tms-docker"
  artifactory_url: https://${registry_url}
  max_images: 10

## Swarm
  SWARM_USER: $NETSNIFF_LDAP_USER
  SWARM_TOKEN: $NETSNIFF_KEYTAB
  DOCKER_PORT: 2375
  SWARM_USER: "root"
  SWARM_CONTROLLER_USER: "netsniff-app"

job:build:
  extends: .build:docker
  only:
    - tags

job:validate:
  extends: .validate:docker
  only:
    - tags

job:clean:
  extends: .clean:docker
  only:
    - tags


job:deploy_rec:
  stage: deploy
  trigger:
    project: service-netsniff/service-netsniff-deployer
    branch: mci-dev
  variables:
    NETSNIFF_HP_VERSION: $CI_COMMIT_REF_NAME
    STACK: $NETSNIFF_STACK
    ENV: rec
  only:
    - tags
  tags:
    - deploy_automation_prod_shared

job:deploy_prod:
  stage: deploy
  trigger:
    project: service-netsniff/service-netsniff-deployer
    branch: mci-dev
  variables:
    NETSNIFF_HP_VERSION: $CI_COMMIT_REF_NAME
    STACK: $NETSNIFF_STACK
    ENV: prod
  only:
    - tags
  tags:
    - deploy_automation_prod_shared    